# Generated by Django 5.0.1 on 2024-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('agreement_type', models.CharField(choices=[('B2B', 'B2B'), ('ZL', 'Zlecenie'), ('1', 'Pełny etat'), ('1/2', '1/2 etatu'), ('3/4', '3/4 etatu')], max_length=30)),
                ('agreement_end_date', models.DateField()),
                ('medical_end_date', models.DateField()),
                ('building_license_end_date', models.DateField()),
                ('default_build', models.CharField(max_length=40)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
