# Generated by Django 5.0.1 on 2024-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-last_name']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='agreement_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agreement_type',
            field=models.CharField(choices=[('B2B', 'B2B'), ('ZL', 'Zlecenie'), ('1', 'Pełny etat'), ('12', '1/2 etatu'), ('34', '3/4 etatu')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='building_license_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_end_date',
            field=models.DateField(null=True),
        ),
    ]
