# Generated by Django 5.0.1 on 2024-02-22 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('substituted', models.CharField(max_length=15)),
                ('substituted_by', models.CharField(max_length=15)),
                ('action_type', models.CharField(choices=[('zn', 'Z_nasze'), ('zi', 'Z_inne'), ('z', 'Zaliczka'), ('w', 'Wolne')], max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('crane', models.CharField(max_length=30)),
                ('duration_hours', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
