# Generated by Django 5.0.1 on 2024-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='duration_hours',
            field=models.IntegerField(null=True),
        ),
    ]
