# Generated by Django 5.0.1 on 2024-03-11 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_substitution_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substitution',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.BooleanField(default=False)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('comments', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
    ]
