# Generated by Django 5.0.1 on 2024-03-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_substitution_options_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='history',
        ),
    ]
