# Generated by Django 5.0.1 on 2024-03-19 13:56

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_holiday_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(null=True)),
                ('type', models.CharField(choices=[('building_license', 'Uprawnienia'), ('medical', 'Badania lekarskie'), ('bhp', 'BHP'), ('other', 'Inne')], max_length=30)),
                ('file', models.FileField(upload_to=myapp.models.employee_directory_path)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
