# Generated by Django 5.0.1 on 2024-03-20 18:59

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=10000, upload_to=myapp.models.employee_directory_path),
        ),
    ]
