# Generated by Django 5.0.1 on 2024-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordtoken',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
