# Generated by Django 5.0.1 on 2024-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_passwordtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtoken',
            name='url_token',
            field=models.CharField(default='', max_length=30),
        ),
    ]
