# Generated by Django 5.0.1 on 2024-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passwordtoken_url_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_token',
            field=models.CharField(default='CBZ7yrqOGvehNaJzjiD6TA1btlo3', max_length=60),
        ),
    ]
