# Generated by Django 5.0.1 on 2024-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_file_file_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_token',
            field=models.CharField(max_length=60),
        ),
    ]
